"""
plot_bifurcation.py
-------------------
Reads data generated by logistic_map_bifurcation.c and plots the bifurcation diagram.

The input file "bifurcation.csv" should contain two columns: (r, x).

Usage:
    python plot_bifurcation.py

Make sure the CSV file is in the same directory as this script.
"""

import matplotlib.pyplot as plt
import pandas as pd

# Read the CSV file (adjust the path if necessary)
data = pd.read_csv("bifurcation.csv", names=["r", "x"])

plt.figure(figsize=(10, 7))
plt.scatter(data["r"], data["x"], s=0.1, color="black")
plt.xlabel("r (Growth Rate)")
plt.ylabel("x (Population)")
plt.title("Logistic Map Bifurcation Diagram")
plt.tight_layout()
plt.show()

